
services:
  zinc:
    restart: always
    image: public.ecr.aws/zinclabs/zincsearch:0.4.10
    container_name: zincsearch
    environment:
      ZINC_FIRST_ADMIN_USER: "admin"
      ZINC_FIRST_ADMIN_PASSWORD: "Complexpass#123"
      ZINC_DATA_PATH: "/data"
    ports:
      - "4080:4080"
    volumes:
      - zinc_data:/data
    networks:
      - mails-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4080"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 10s
networks:
  mails-network:
    external: true
    driver: bridge   
volumes:
  zinc_data:
  