services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    container_name: mails_api
    image: mails_api
    env_file:
      - .env
    networks:
      - mails-network

networks:
  mails-network:
    external: true
    driver: bridge
