FROM golang:1.23.4-alpine AS builder


WORKDIR /app

ENV APP_MODE=release

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN  go build -o api .

FROM alpine:3.21.3

RUN apk --no-cache add ca-certificates

COPY --from=builder /app/api /api

EXPOSE $SERVER_PORT

CMD ["/api"]